name: Cek Proxy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run proxy checker
        run: python proxychecker.py

      - name: Commit result
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          if [ -f result.txt ]; then
            git add result.txt
            git commit -m "✅ Checked proxies" || echo "No changes"
            git push
          else
            echo "❌ result.txt tidak ditemukan, melewati commit."
