name: Check Proxy List

on:
  schedule:
    - cron: "15 */6 * * *"
  workflow_dispatch:

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run proxy checker
        run: python proxyChecker.py -l proxies.txt -o result.txt -t 10

      - name: Commit result.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add result.txt
          git commit -m "Update checked proxies" || echo "No changes"
          git push
