name: Get Proxies and push proxies

on:
  schedule:
    - cron: '0 * * * *'  # Setiap jam
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape_proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Proxy Scraper
        run: python proxyscrape.py

      - name: Commit scraped proxies
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update proxy list"
          file_pattern: proxies.txt
