name: Get Proxy List

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  get-proxies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run proxy scraper
        run: python proxyscrape.py

      - name: Commit proxies.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add proxies.txt
          git commit -m "Update proxy list" || echo "No changes"
          git push
