name: Get Proxy

on:
  schedule:
    - cron: "0 0 * * *"  # Setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run proxy scraper
        run: python proxyscrape.py

      - name: Remove duplicate proxies
        run: sort -u proxies.txt -o proxies.txt

      - name: Commit scraped proxies
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add proxies.txt
          git commit -m "🔄 Update proxies" || echo "No changes"
          git push
